/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.app.hub;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;

/**
 *
 * @author Gio Andrew Briones
 */
public class quizPanel extends javax.swing.JPanel {

    /**
     * Creates new form quizPanel
     */
    public quizPanel() {
        initComponents();
        generateButtonGroup();
        showQuestion(0);
    }
    
    private void generateButtonGroup()
    {
        ButtonGroup grp = new ButtonGroup();
        grp.add(opt1);
        grp.add(opt2);
        grp.add(opt3);
        grp.add(opt4);
    }
    
    private int currentIndex = 0;
    
    class quizQuestions {
        String questionText;
        String[] options;
        int correctAnswer;
        
        public quizQuestions(String text, String[] opt, int answer)
        {
            questionText = text;
            options = opt;
            correctAnswer = answer;
        }
    }
    
    public void showQuestion(int index)
    {
        quizQuestions q = quiz.get(index);
        lblQuestion.setText(q.questionText);
        opt1.setText(q.options[0]);
        opt2.setText(q.options[1]);
        opt3.setText(q.options[2]);
        opt4.setText(q.options[3]);
    }
    
    private ArrayList<quizQuestions> quiz = new ArrayList<>(List.of(
            new quizQuestions("What is 5 + 5", new String[]{"5", "10", "15", "20"}, 1),
            new quizQuestions("What is 10 + 10", new String[]{"15", "5", "20", "1"}, 2)
    ));
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 0, 102));
        setPreferredSize(new java.awt.Dimension(831, 536));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(204, 204, 255));
        lblQuestion.setText("This is a sample question");
        add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 1130, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Math Quiz");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 118));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("QUESTION:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 350, 112));

        opt1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        opt1.setForeground(new java.awt.Color(204, 204, 255));
        opt1.setText("Option 1");
        opt1.setContentAreaFilled(false);
        add(opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 440, 50));

        opt2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        opt2.setForeground(new java.awt.Color(204, 204, 255));
        opt2.setText("Option 1");
        opt2.setContentAreaFilled(false);
        add(opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 440, 47));

        opt3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        opt3.setForeground(new java.awt.Color(204, 204, 255));
        opt3.setText("Option 1");
        opt3.setContentAreaFilled(false);
        add(opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 440, 47));

        opt4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        opt4.setForeground(new java.awt.Color(204, 204, 255));
        opt4.setText("Option 1");
        opt4.setContentAreaFilled(false);
        add(opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 610, 440, 47));

        submitBtn.setBackground(new java.awt.Color(204, 0, 204));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(204, 204, 255));
        submitBtn.setText("SUBMIT ANSWER");
        submitBtn.addActionListener(this::submitBtnActionPerformed);
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 790, 249, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        currentIndex++;
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}

